/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universitycourseregistrationsystem;

/**
 *
 * @author mehmet
 */

import javax.swing.*;
import java.awt.event.*;
import java.io.IOException;
import java.util.HashMap;


public class loginPage extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginPage.class.getName());
    
    HashMap<String, Course> allCourses = new HashMap<>();
    HashMap<String, Student> allStudents = new HashMap<>();
    
    public loginPage() {
        initComponents();
        
        this.setTitle("Login Page");
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        
        try {
            allStudents = FileManager.initAllStudents();
            allCourses = FileManager.initAllCourses(allStudents);
            FileManager.initStudentCourses(allStudents, allCourses);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, " File not found during initializing courses! ");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, " An error has occurred during initialization! ");
        }
        
        loginBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                //Check the fields if there are any empty field
                try {
                    if ("".equals(idField.getText()) || "".equals(passwordField.getText()) ) {
                        throw new IOException("");
                    }
                   
                    
                    String userLine = FileManager.searchUserByID1(idField.getText());
                    String password = passwordField.getText();
                    
                    //Parsing the information into its elements
                    String[] parsedLine = userLine.split("\\|");
                    
                    if (FileManager.isPasswordCorrect(parsedLine, password)) {
                        if (parsedLine[2].trim().equals(Types.STUDENT.toString())) {
                            studentMenuPage smp = new studentMenuPage(allStudents.get(parsedLine[3]), allCourses);
                            System.out.println("Student object is initialized! ID: " + allStudents.get(parsedLine[3]).getUserID());
                            
                            smp.setVisible(true);   
                        }
                        
                        else if (parsedLine[2].trim().equals(Types.PROFESSOR.toString())) {
                            //Create the professor object with the given information line and pass to the professorMenuPage
                            Professor professor = FileManager.initProfessor(parsedLine , allCourses);
                            System.out.println("Professor object is initialized! ID: " + professor.getUserID());
                            
                            professorMenuPage pmp = new professorMenuPage(professor, allCourses, allStudents);
                            
                            pmp.setVisible(true);   
                        }
                        
                        else if (parsedLine[2].trim().equals(Types.ADMIN.toString())) {
                            //Create the admin object with the given information line and pass to the adminMenuPage
                            Admin admin = FileManager.initAdmin(parsedLine);
                            System.out.println("Admin object is initialized! ID: " + admin.getUserID());
                            adminMenuPage amp = new adminMenuPage(admin);
                            
                            amp.setVisible(true);
                        }
                        
                        loginPage.this.dispose();
                    }
                    
                    
                } catch (IOException ex) {
                    errorLbl.setText(" Empty field or fields! ");
                } catch (FileNotFoundException ex) {
                    errorLbl.setText(" File not found! ");
                } catch (UserNotFoundException ex) {
                    errorLbl.setText(" User not found! ");
                } catch (PasswordIsWrongException ex) {
                    errorLbl.setText(" Password is wrong! ");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel4 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("User ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        idField.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        getContentPane().add(idField, gridBagConstraints);
        idField.getAccessibleContext().setAccessibleName("idField");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        passwordField.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        getContentPane().add(passwordField, gridBagConstraints);
        passwordField.getAccessibleContext().setAccessibleName("passwordField");
        passwordField.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("University Course");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Login Page");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        loginBtn.setText("Login");
        loginBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        jPanel1.add(loginBtn, gridBagConstraints);
        loginBtn.getAccessibleContext().setAccessibleName("loginBtn");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel1.add(errorLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginPage().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLbl;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
